name: Trigger auto deployment for deepface

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/deepface-AutoDeployTrigger-9b99b0ed-316c-40eb-b490-f487ab6aad95.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEEPFACE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEEPFACE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEEPFACE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.DEEPFACE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEEPFACE_REGISTRY_PASSWORD }}
          containerAppName: deepface
          resourceGroup: xinghan
          imageToBuild: xinghanking/deepface:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


